### ISSUE TITLE
Current path of the Central Note

### ISSUE THREAD

**Issue by thanushkas** [Robin-Haupt-1/Obsidian-Map-of-Content#105]
Thanks for the great plugin.
I am using Obsidian Vault in my personal laptop and the office computer. I use OneDrive to sync my notes in both places. However, when I write notes in Obsidian in the laptop and in the next day, I could work in the office computer Obsidian notes. In every time, I have to update the current path of the central note, if I change the device. Could you please add a relative path for it?

**Comment by Robin-Haupt-1** [comment]
Hi, if you used Obsidian Sync I believe it would sync the path to the central note when you change it

**Comment by thanushkas** [comment]
Hi,
Thanks for your reply. It has been solved. I have no clue how would be solved it. Thanks once again.
