### ISSUE TITLE
Blank tabs will automatically open

### ISSUE THREAD

**Issue by wwjCMP** [Robin-Haupt-1/Obsidian-Map-of-Content#108]
When I click on the pinned tab, two blank tabs will automatically open.

**Comment by Robin-Haupt-1** [comment]
Please provide more details. What version of Obsidian are you using, and what do you mean by pinned tab? Pinned within the MOC addon or within Obsidian? Maybe provide screenshots if helpful. Thank you

**Comment by wwjCMP** [comment]
![GIF 2023-6-25 3-51-59](https://github.com/Robin-Haupt-1/Obsidian-Map-of-Content/assets/32979859/aa88883f-86b2-4e1f-886e-5c12454afcd6)
Obsidian v1.3.5. 
After I deactivated this plugin, the issue above disappeared.

**Comment by Robin-Haupt-1** [comment]
Thank you for the information. Unfortunately I can't recreate the issue right now. Does the problem occur again if you activate the plugin and disable all other plugins? 

Have you tried restarting Obsidian?

Please make sure you have the latest version of the plugin installed also.

**Comment by byerun** [comment]
I see this when making a pinned tab go from non-visible to visible on the Windows version of Obsidian 1.3.5 with Map of Content 0.1.18.  This occurs on both my work and personal computer.

I created a vault with only the MOC plugin as the only community plugin and disabled all the core plugins and the new tabs still show up when a pinned tab becomes visible.

**Comment by robin-haupt-legalbird** [comment]
I'll try to replicate it on Windows. If other people also experience this problem, please leave a comment or upvote here, so i can gauge the severity of the issue.

**Comment by Robin-Haupt-1** [comment]
Update: i've been able to replicate it (on Linux btw.) and will starting working on a fix

**Comment by jkamenik** [comment]
I am having this issue as well on a Mac.  Version `0.1.18` of the plugin, and `1.3.5` of Obsidian.

My issue is also with pinned tabs.  Unpinned tabs seem to be fine.

Any idea when the fix will go out, cause this is a a super useful plugin.

**Comment by Robin-Haupt-1** [comment]
The fix is out now. Happy note taking!
