### ISSUE TITLE
Does not work with Homepage plugin

### ISSUE THREAD

**Issue by PPN010** [Robin-Haupt-1/Obsidian-Map-of-Content#109]
I enabled the Homepage plugin and this plugin, set up a workspace containing the plugin's leaf view, and specified that this workspace would open automatically when opened. When I reopened the library, the left and right leaves and the editing page in the middle were completely blank. When I closed the homepage or this plugin, the error disappeared

- Homepage 3.2
- MOC 1.0

**Comment by PPN010** [comment]
## Performance and error messages when errors occur

![image](https://github.com/Robin-Haupt-1/Obsidian-Map-of-Content/assets/90024544/7bc8901d-e01b-4b90-ad8a-924c80a62781)

---

caught (in promise) TypeError: Cannot read properties of null (reading 'view')
    at MOCView.rerender (plugin:map-of-content:2937:63)
    at MOCView.init (plugin:map-of-content:2927:14)
    at eval (plugin:map-of-content:2909:60)
    at t.onLayoutReady (app.js:1:1926622)
    at new MOCView (plugin:map-of-content:2909:35)
    at eval (plugin:map-of-content:4540:65)
    at t.<anonymous> (app.js:1:1782682)
    at app.js:1:236930
    at Object.next (app.js:1:237035)
    at a (app.js:1:235753)

---

plugin:map-of-content:2937 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'view')
    at MOCView.rerender (plugin:map-of-content:2937:63)
    at MOCPlugin.rerender (plugin:map-of-content:4596:23)
    at DBManager.update (plugin:map-of-content:173:25)

**Comment by BoltLi** [comment]
Also conflict with obsidian workspace function.  Turn on the obsidian core function 'workspace' and this plugin, obsidian will go wrong with only blank, and unbale to open any file in obsidian.
![image](https://github.com/Robin-Haupt-1/Obsidian-Map-of-Content/assets/42888380/39ece0c3-ab3f-4820-8f9f-0c8225b8c8b4)
@Robin-Haupt-1

**Comment by Robin-Haupt-1** [comment]
Thank you for creating the issue, i will look into it ASAP

**Comment by adrianghnguyen** [comment]
I would also like to chime in and say that I am getting the same issue. Disabling the plugin is necessary for me at the moment since it conflicts with workspaces.

**Comment by Robin-Haupt-1** [comment]
Sorry for the long wait. It's been incredibly busy at work lately. I'm releasing the fix now.

**Comment by adrianghnguyen** [comment]
Thank you so much for your work. Appreciate it!

**Comment by PPN010** [comment]
Marveling at the efficiency of the repair, it was amazing !


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Robin-Haupt-1/Obsidian-Map-of-Content"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月2日(星期六) 凌晨3:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Robin-Haupt-1/Obsidian-Map-of-Content] Does not work with Homepage plugin (Issue #109)





 
Closed #109 as completed.
