### ISSUE TITLE
Config dropdown picker too limiting

### ISSUE THREAD

**Issue by davecan** [Robin-Haupt-1/Obsidian-Map-of-Content#27]
Config screen has a drop down picker to select the central note. However for large vaults that will be prohibitive, also it doesn't scroll. Mine goes right off the bottom of the screen and I can only select a handful of notes (maybe 40 so under 4%) out of the 1000+ I currently have.

Also picking a note from that list and clicking rebuild map of content doesn't appear to do anything. I picked an existing note in the vault and clicked the button to save and regenerate the MOC, then opened the note, but nothing changed. I reordered the vault by created time and no other note was created.

Excellent plugin idea though, look forward to seeing it evolve.

**Comment by Robin-Haupt-1** [comment]
Thank you for contributing!

You can enter text in the drop down picker field to filter the entries. I'm going to make that more specific in the settings screen.

I'll try to make it so it doesn't try to display all the notes if it's too many.

The MOC will get displayed in the plugins own view, not saved to a file. Can you see that? If not, or it doesn't show anything, can you try reloading the plugin in the settings or restarting Obsidian?

**Comment by davecan** [comment]
Oh interesting I didn't even notice it had a pane. My sidebars are usually collapsed. 

So from what I see it shows the path _from_ the currently open note to the _central note_, not from the central note towards this note. That wasn't obvious when I first looked at the screenshot. The hierarchy shown implies the topmost node in the hierarchy is the "central" note.

I would like to see that if possible, or maybe it can be a config item. 

So from the example screenshot, the order would be the reverse.

```
Central note → Animals → Mammals
```

That functions more like a breadcrumb from a centrally defined note, which seems to be the intent.

I also don't understand the hierarchy. In my vault I open a note N that has 3 links A, B, and C. The MOC pane then shows me something that looks like this:

```
N ⮕ A ⬅ (a bridge note) ⮕ The central note

N
  A
  C
```

It's not clear why it picked only links A and C but excluded link B.

This may also just be an issue with my interpretation though.
