### ISSUE TITLE
Feature Request: Allow Users to Exclude Files/Folders

### ISSUE THREAD

**Issue by eleanorkonik** [Robin-Haupt-1/Obsidian-Map-of-Content#48]
I love Zoottelkeeper but I would love to exclude the auto-generated indexes it creates from this to make it more organic, or to exclude certain the contents of certain folders from the map. Does that make sense?

**Comment by eleanorkonik** [comment]
Oh awesome! 

And yeah, excluding individual files would be awesome. I mostly want to exclude these:

> %% Zoottelkeeper: Beginning of the autogenerated index file list  %%

But I'm fine to do it through YAML or tags if searching all the files for regex matches isn't performant.

**Comment by Robin-Haupt-1** [comment]
Sorry, i meant searching the file names for matches or regex expressions, not the content. Would that be good for you? Searching the files indeed seems to take very long (i've tested if), but it may still be a good optional feature (After all the files wouldn't need to be reread unless they're modified date has changed)

Excluding tags is definitely something i want to implement.

**Comment by eleanorkonik** [comment]
Ah! I understand now, sorry. I can work with filenames — I think the zoottelkeeper lets me prepend with "_index" and now that I use folder notes I don't care that it's ugly lol. 

Thank you!!!
