### ISSUE TITLE
Change the design of the MOC tree

### ISSUE THREAD

**Issue by Robin-Haupt-1** [Robin-Haupt-1/Obsidian-Map-of-Content#54]
maybe move away from the dotted lines style to something more modern.

**Comment by tyf2018** [comment]
Hi， @Robin-Haupt-1 
I am very happy to hear this. I like this plugin very much, but I have to admit that I am not used to the dotted style.

In addition, I want to change the dotted line to a solid line, and customize the color and thickness. How should I modify the css? I haven't found a valid css parameter in the developer background.
![2021-11-19_09-45-37](https://user-images.githubusercontent.com/56342788/142549736-0b319c75-b3fe-44c8-90d9-a403ed65c5b9.jpg)

Best Regards.

**Comment by Robin-Haupt-1** [comment]
Hi tyf2108,

what do you mean by "developer background" in 
 
> I haven't found a valid css parameter in the developer background.  

? Do you mean the developer console or the plugins settings tab?

There is no option to change the design without changing the source code. I have made a few changes. How do you like this look? I think it's much better and i'll probably release an update with this style soon.


![Bildschirmfoto von 2021-11-19 16-15-31](https://user-images.githubusercontent.com/85873542/142646460-587b2f0d-c897-41e8-b2cb-461badeb7ea0.png)

 I'm curious, how would you modify the style if there was an option to?

**Comment by tyf2018** [comment]
> Do you mean the developer console or the plugins settings tab?

Yes, this:
![image](https://user-images.githubusercontent.com/56342788/142715609-a606ef07-5f9c-4a9f-a5b9-ddd7d31dd241.png)

The new design is pretty good, and I look forward to its release soon.

At present, for the MOC tree, I hope to quickly identify the hierarchical relationship to which the notes belong, so I customized the font color, and the effect is similar to this:
![image](https://user-images.githubusercontent.com/56342788/142715922-90d23a66-d65b-4cae-9334-42e293cf302a.png)

At present, it is still a bit ugly, but it does help me quickly identify hierarchical relationships. This is the css code:

> /*MOC_map of connnet插件*/
> .workspace-leaf-content[data-type="map-of-content"] .view-content{
> 	font-size: 0.95em;
> }
> div#main_moc_div {
> 	line-height: 1.5 !important;
> 	font-size: 0.9em !important;
> 	color: var(--text-header2);
> }
> .workspace-leaf-content[data-type="map-of-content"] li.container {
> 	color: var(--text-header2);
> }
> .workspace-leaf-content[data-type="map-of-content"] ul li:last-child {
>     margin-left: -14px;
> }
> .workspace-leaf-content[data-type="map-of-content"] li p {
> 	line-height: 1.3 !important;
> 	margin-bottom: 1px !important;
> }
> /*.workspace-leaf-content[data-type="map-of-content"] li.container a.link {
> }*/
> /*MOC tree悬停*/
> .workspace-leaf-content[data-type="map-of-content"] ul:hover {
> 	box-shadow: none !important;
> }
> /*MOC tree竖向边框*/
> .workspace-leaf-content[data-type="map-of-content"] li {
> 	border: none !important;
> }
> /*MOC tree横向边框*/
> .workspace-leaf-content[data-type="map-of-content"] li.container ul {
> 	border: none !important;
> 	font-size: 1.03em !important;
> 	background-color: var(--background-nav-alt);
> }
> .workspace-leaf-content[data-type="map-of-content"] li.container ul a.link {
> 	color: var(--wangzhi-font-color2);
> }
> .workspace-leaf-content[data-type="map-of-content"] li.container ul ul {
> 	font-weight: normal;
> 	font-size: 0.95em !important;
> 	background-color: var(--background-primary);
> }
> .workspace-leaf-content[data-type="map-of-content"] li.container ul ul a.link {
> 	color: var(--doublelink-color);
> }
> .workspace-leaf-content[data-type="map-of-content"] li.container ul ul ul {
> 	font-size: 0.98em !important;
> 	padding-left: 30px !important;
> }
> .workspace-leaf-content[data-type="map-of-content"] li.container ul ul ul a.link {
> 	color: var(--file-embed-title);
> }
> .workspace-leaf-content[data-type="map-of-content"] li.container ul ul ul ul {
> 	padding-left: 30px !important;
> }
> .workspace-leaf-content[data-type="map-of-content"] li.container ul ul ul ul a.link {
> 	color: rgb(88, 153, 228);
> }
> .workspace-leaf-content[data-type="map-of-content"] li.container ul ul ul ul ul a.link {
> 	color: var(--text-accent);
> }
> .workspace-leaf-content[data-type="map-of-content"] li.container ul ul ul ul ul ul a.link {
> 	color: tomato;
> }
> .workspace-leaf-content[data-type="map-of-content"] li.container ul ul ul ul ul ul ul a.link {
> 	color: teal;
> }
> .workspace-leaf-content[data-type="map-of-content"] li.container ul ul ul ul ul ul ul ul a.link {
> 	color: red;
> }
> .workspace-leaf-content[data-type="map-of-content"] li.container ul ul ul ul ul ul ul ul ul a.link {
> 	color: violet;
> }
> .workspace-leaf-content[data-type="map-of-content"] li.container ul ul:hover {
> 	box-shadow: none !important;
> }

**Comment by Robin-Haupt-1** [comment]
Wow, very interesting! Thanks for sharing that. Working with colors is a nice idea, maybe i'll add that functionality to the plugin.

**Comment by tyf2018** [comment]
By the way, there is a small suggestion. Can this icon be replaced with icons such as right arrow and down arrow? Reason: It is very similar to folding and unfolding, so it is difficult to distinguish.

> ![image](https://user-images.githubusercontent.com/56342788/142748089-e65f41ce-e550-404c-b418-83cb74261df9.png)

**Comment by Robin-Haupt-1** [comment]
Do you mean thats unfolded looks too similar to folded?

Now that i think about it, maybe it would help to switch to something like this: https://iconmonstr.com/arrow-37-svg/

Since the current icon has this little ege on the top/left side, it may be harder to distuingish which way it points.

**Comment by Robin-Haupt-1** [comment]
Or maybe this would be even better? https://iconmonstr.com/arrow-25-svg/

**Comment by tyf2018** [comment]
Hi， @Robin-Haupt-1 
Would you consider using an arrow icon like this? When collapsed, the right arrow is displayed and the color becomes dimmed, and when expanded, it is displayed as the down arrow and the color becomes brighter.

> ![image](https://user-images.githubusercontent.com/56342788/142760399-c9e22649-fc84-456c-9ecd-0d3e074784e0.png)

**Comment by Robin-Haupt-1** [comment]
I would rather not use an arrow like in your picture but stay with the simple triangles, because i think it's more intuitive and a common icon to use in collapsing trees. 

Maybe making the arrows colorful, and maybe making collapsed ones fade is a good idea. I'll think about it.

I like the idea of having the background highlighted on hover. I like the style in your video in general. Can you send me the css for that? Maybe i could use some things from it.

**Comment by tyf2018** [comment]
> I would rather not use an arrow like in your picture but stay with the simple triangles, because i think it's more intuitive and a common icon to use in collapsing trees.

If it is a triangle, I personally think it might be easy to confuse folding and unfolding. In short, my idea is that the collapsed and expanded icons should be easy to distinguish. Or use triangles when folding? But use another shape when unfolding, such as a square? Hahaha, just say it casually.

> Can you send me the css for that? Maybe i could use some things from it.

Regarding css, I only have this entire file, please check it.

[Blue Topaz.zip](https://github.com/Robin-Haupt-1/Obsidian-Map-of-Content/files/7576217/Blue.Topaz.zip)

**Comment by Robin-Haupt-1** [comment]
Do you also think it would be hard to tell apart the two states with this arrow? https://iconmonstr.com/arrow-25-svg/ It is like a real arrow just without the tail :)

Regarding the css, in the video you seem to have my plugin with hover background and without the borders around the <li> elements? I really like how it looks. Can you send me the CSS for that? 

And i am curios, how exactly do you make all these changes to the plugins apperance? Do you put the CSS files in the CSS snippets folder?

**Comment by tyf2018** [comment]
> Do you also think it would be hard to tell apart the two states with this arrow?

It may be that everyone’s feelings are different. How do I find arrows with tails easier to distinguish?🤣

> how exactly do you make all these changes to the plugins apperance? Do you put the CSS files in the CSS snippets folder?

In fact, that is not the MOC tree of the MOC plug-in, but the view interface of the Obsidian core plug-in file list . Because I haven't found a valid css parameter, so I don't know how to modify the css style of the MOC tree.

The connection of the file list is controlled by this css:
[文件列表.zip](https://github.com/Robin-Haupt-1/Obsidian-Map-of-Content/files/7576265/default.zip)

The principle is the same, I think the MOC tree can also achieve the hovering effect of the connection.

**Comment by Robin-Haupt-1** [comment]
> It may be that everyone’s feelings are different. How do I find arrows with tails easier to distinguish?

This may also be because you have removed the borders with your custom CSS. They probably make it easier to discern hierarchy, and that tells you if an item is expanded in this way: If it has a button to expand, but you can't see any descendants, it's collapsed.

**Comment by tyf2018** [comment]
Hi， @Robin-Haupt-1 
I may have solved the style of the hover effect, the effect is as follows:

https://user-images.githubusercontent.com/56342788/143168922-28ce3436-3f9f-47cd-99b4-e58bcc9ed81b.mp4

/*MOC tree竖向边框*/
.workspace-leaf-content[data-type="map-of-content"] li {
	border-left: none !important;
}
.workspace-leaf-content[data-type="map-of-content"] li:hover,
.workspace-leaf-content[data-type="map-of-content"] li li:hover,
.workspace-leaf-content[data-type="map-of-content"] li li li:hover,
.workspace-leaf-content[data-type="map-of-content"] li li li li:hover,
.workspace-leaf-content[data-type="map-of-content"] li li li li li:hover,
.workspace-leaf-content[data-type="map-of-content"] li li li li li li:hover {
	border-left: 3px solid var(--text-header2) !important;
}
/*MOC tree横向边框*/
.workspace-leaf-content[data-type="map-of-content"] li.container ul {
	border: none !important;
	font-size: 1.03em !important;
}

**Comment by Robin-Haupt-1** [comment]
Thanks, but i was thinking rather about the background underlying the whole row / line being highlighted on hover.

I think you could stop the hover from moving the text to the right by giving the lis a 
border-left: 3px solid transparent;
