### ISSUE TITLE
Add option to automatically refresh the MOC when any note is changed

### ISSUE THREAD

**Issue by Robin-Haupt-1** [Robin-Haupt-1/Obsidian-Map-of-Content#55]
If the user doesn't have too many notes and/or a fast computer, this shouldn't be a problem

**Comment by Robin-Haupt-1** [comment]
or even better, monitor the notes for changes in links and only update then. or darken out the MOC view and update it when the user clicks on it to use it again / show a button to update it when links have changed inside the view (related: #56 )

**Comment by Robin-Haupt-1** [comment]
@chrisgrieser, check out the latest update!

**Comment by chrisgrieser** [comment]
thanks!
