### ISSUE TITLE
Provide a search interface

### ISSUE THREAD

**Issue by S-Wil** [Robin-Haupt-1/Obsidian-Map-of-Content#59]
Brilliant plugin!

I would like to see this as a search interface, eg:
home:/start.md depth:3 tag:#topic -folder:/templates
including the ability to "favourite" searches.

I have many uses for this and one MoC is too limiting. Per the above restricting to certain tags would be awesome, along with limiting to and/or excluding certain folders.

**Comment by Robin-Haupt-1** [comment]
Hi,

you can already exclude folders and filter file names in the settings.

Filtering tags is something i have plans for, as is keeping several Maps of content with different Central Notes and different settings. 

For a compromise, for the time being you could link any note you would want to be a central note to your current central note so they're directly underneath it in the tree.

**Comment by S-Wil** [comment]
Thanks for your feedback and while I still like the idea of a search approach I understand you have a different plan.

FYI could you also consider limiting to a set of folders and not just excluding folders?

**Comment by Robin-Haupt-1** [comment]
I've opened an issue for that: #61
