### ISSUE TITLE
package does not build due to ... in version

### ISSUE THREAD

**Issue by trashhalo** [Robin-Haupt-1/Obsidian-Map-of-Content#68]
npm seems to hate the `...` that is in package json. Its easy to work around by sticking 1.0.0 in there is there a reason its there? Might want to add something to the readme if you want to keep that. like a contributors section

```
➜  Obsidian-Map-of-Content git:(main) ✗ npm run build
npm ERR! Invalid version: "..."
```

**Comment by Robin-Haupt-1** [comment]
Hi trashhalo,

I've fixed that.
