### ISSUE TITLE
Reverse the display order of the "shortest path from the central note to the currently open note"?

### ISSUE THREAD

**Issue by Brettelectric** [Robin-Haupt-1/Obsidian-Map-of-Content#76]
I would love it if there was an option in settings to just reverse the displayed order of the link/note path that we see at the top of the 'Map of Content' pane.

It just makes more sense to me to have the 'home' MOC appear first, and then work my way down to the current note, rather than starting with the current note, and working back up. 

This would make it more like the Windows Explorer file path display. Thanks!

**Comment by Robin-Haupt-1** [comment]
Thank you for the feedback!

This has been requested a few times, so i'll try to implement it soon.

**Comment by Brettelectric** [comment]
That would be great! Great addon btw!

**Comment by Robin-Haupt-1** [comment]
I just released the update with this feature.

**Comment by Brettelectric** [comment]
Nice! It works great, thanks!

________________________________
