### ISSUE TITLE
Add command to re-open the widget

### ISSUE THREAD

**Issue by areshytko** [Robin-Haupt-1/Obsidian-Map-of-Content#80]
There's no command in a command palette to open a widget. So If I closed it I don't know how to open it again

**Comment by Robin-Haupt-1** [comment]
You can disable the plugin in Obsidian settings and enable it again, that will open a new view.

Thanks for the suggestion of using a command to do that though, i hadn't thought of that. Maybe i'll do that.

**Comment by areshytko** [comment]
Yes, thank you. But it smells more like a hack. Plus, personally, for me it's inconvenient to look at the map at the sidebar, It's much better to look at it in a horizontal split. And this scenario requires having a command in a command palette to invoke a map view. 

If you look at the other native functionality - backlinks for example. It's done that way - they have a command to invoke them. So it's good also for UX consistency.

Please consider implementing it. And thank you for the great plugin!

**Comment by Robin-Haupt-1** [comment]
Thanks for the information that this resembles native functionality. I will probably add this soon.

If you use the plugin in split view, do you also experience that the view will say 'No file is open' once you click on it?
You're the first to have mentioned they use it that way, but i think it's a good idea to do that. I could make this annoying behavior go away by making the view stay on the last opened file if no file is opened. Does that sound useful to you?

**Comment by areshytko** [comment]
Yes, very! Thank you so much. A🍺  from me

**Comment by Robin-Haupt-1** [comment]
I've added this issue, i'll work on it soon: https://github.com/Robin-Haupt-1/Obsidian-Map-of-Content/issues/81

**Comment by Robin-Haupt-1** [comment]
@areshytko 

The latest release should function much better with split mode. I'm sorry i couldn't fix this sooner.
