### ISSUE TITLE
Cmd-click replaces current pane instead of opening new pane

### ISSUE THREAD

**Issue by creadian** [Robin-Haupt-1/Obsidian-Map-of-Content#98]
Hi, I think your plugin is extremely useful! One thing i encountered: When I cmd-click on a link in the Map-of-Content sidebar, a new pane gets opened, but it stays empty and instead the clicked note gets opened inside the current pane. 
I'm on MacOS, latest insider version, latest version of plugin. Very likely that some other plugin causes the issue, let me know if you'd like me to investigate further.
Thank you!

**Comment by Robin-Haupt-1** [comment]
Hello, thank you for the bug report.

That is indeed a bug, and i can reproduce it on 0.13.33 without any other plugins active. Recent versions of Obsidian must have changed how opening a note in a new pane works.

**Comment by Robin-Haupt-1** [comment]
This will be fixed in the new version

**Comment by Robin-Haupt-1** [comment]
the fix is out now
